/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_managment_syatem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;

/**
 *
 * @author yash
 */
public class addFees extends javax.swing.JFrame {

    /**
     * Creates new form addFees
     */
    public addFees() {
        initComponents();
        displayCashFirst();
        fillComboBox();
        int receipt_no=getReceiptNo();
        txtReceiptNo.setText(Integer.toString(receipt_no));
    }
    public  void displayCashFirst(){
        lblDdNo.setVisible(false);
        lblChequeNo.setVisible(false);
        txtChequeNo.setVisible(false);
        txtDDNo.setVisible(false);
        lblBankName1.setVisible(false);
        txtBankName1.setVisible(false);
        
    }
    public boolean validation(){
        if(txtHead.getText().equals("")){
            JOptionPane.showMessageDialog(this,"please enter user name.");
            return false;
        }
       if(DateChosser.getDate() == null){
           JOptionPane.showMessageDialog(this, "please select a date.");
           return false;
       }
       if(txtAmountFirst.getText().equals("") || txtAmountFirst.getText().matches("[0-9]+") == false){
           JOptionPane.showMessageDialog(this,"please enter amount.");
           return false;
       }
       if(comboBoxPayment.getSelectedItem().toString().equalsIgnoreCase("Cheque")){
           if(txtChequeNo.getText().equals("")){
               JOptionPane.showMessageDialog(this,"please enter cheque number.");
               return false;
           }
           if(txtGSTNo.getText().equals("")){
               JOptionPane.showMessageDialog(this,"please enter bank name.");
               return false;
           }
       }
       if(comboBoxPayment.getSelectedItem().toString().equalsIgnoreCase("DD")){
           if(txtDDNo.getText().equals("")){
               JOptionPane.showMessageDialog(this, "please enter dd no.");
               return false;
           }
           if(txtBankName1.getText().equals("")){
               JOptionPane.showMessageDialog(this,"please enter bank name.");
               return false;
           }
       }
       if(comboBoxPayment.getSelectedItem().toString().equalsIgnoreCase("Card")){
           if(txtBankName1.getText().equals("")){
               JOptionPane.showMessageDialog(this,"please enter bank name");
               return false;
           }
       }
        return true;
    }
   public void fillComboBox(){
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_managment?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                PreparedStatement pst=con.prepareStatement("select CNAME from course");
                ResultSet rs=pst.executeQuery();
                while(rs.next()){
                    comboBoxCourse1.addItem(rs.getString("CNAME"));
                }
       }catch(Exception e){
           e.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSideBar = new javax.swing.JPanel();
        panelLogOut = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSearchRecords = new javax.swing.JPanel();
        btnSearchRecords = new javax.swing.JLabel();
        panelEditCourse = new javax.swing.JPanel();
        btnEditCourse = new javax.swing.JLabel();
        panelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panelViewAllRecords = new javax.swing.JPanel();
        btnViewAllRecords = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelParent = new javax.swing.JPanel();
        lblChequeNo = new javax.swing.JLabel();
        lblReceiptNo = new javax.swing.JLabel();
        lblDdNo = new javax.swing.JLabel();
        lblModeOfPayment = new javax.swing.JLabel();
        txtGSTNo = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtReceiptNo = new javax.swing.JTextField();
        txtChequeNo = new javax.swing.JTextField();
        DateChosser = new com.toedter.calendar.JDateChooser();
        panelChild = new javax.swing.JPanel();
        lblPaymentCollage = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txtLastDate = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        txtFirstDate = new javax.swing.JTextField();
        lblReceiverSignature = new javax.swing.JLabel();
        lblRecievedFrom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblCourse = new javax.swing.JLabel();
        lblRemark = new javax.swing.JLabel();
        lblSgst = new javax.swing.JLabel();
        txtSumTotal = new javax.swing.JTextField();
        txtTotalInWords = new javax.swing.JTextField();
        txtCgst = new javax.swing.JTextField();
        txtAmountFirst = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtSgst = new javax.swing.JTextField();
        lblSrNo = new javax.swing.JLabel();
        txtHead = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneRemark = new javax.swing.JTextPane();
        lblTotalInWords = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        lblHead = new javax.swing.JLabel();
        lblCgst = new javax.swing.JLabel();
        comboBoxCourse1 = new javax.swing.JComboBox<>();
        txtHead1 = new javax.swing.JTextField();
        txtRollNo = new javax.swing.JTextField();
        txtDDNo = new javax.swing.JTextField();
        comboBoxPayment = new javax.swing.JComboBox<>();
        txtBankName1 = new javax.swing.JTextField();
        lblBankName1 = new javax.swing.JLabel();
        lblGSTNo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSideBar.setBackground(new java.awt.Color(255, 102, 102));
        panelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogOut.setBackground(new java.awt.Color(255, 102, 102));
        panelLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelLogOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/exit.png"))); // NOI18N
        btnLogOut.setText("        Logout");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });
        panelLogOut.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 50));

        panelSideBar.add(panelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 320, 50));

        panelHome.setBackground(new java.awt.Color(255, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/home.png"))); // NOI18N
        btnHome.setText("      HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 50));

        panelSideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 320, 50));

        panelSearchRecords.setBackground(new java.awt.Color(255, 102, 102));
        panelSearchRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSearchRecords.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecords.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSearchRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/search2.png"))); // NOI18N
        btnSearchRecords.setText("      Search Records");
        btnSearchRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordsMouseExited(evt);
            }
        });
        panelSearchRecords.add(btnSearchRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 60));

        panelSideBar.add(panelSearchRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, 50));

        panelEditCourse.setBackground(new java.awt.Color(255, 102, 102));
        panelEditCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEditCourse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelEditCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/edit2.png"))); // NOI18N
        btnEditCourse.setText("      Edit Course");
        btnEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseExited(evt);
            }
        });
        panelEditCourse.add(btnEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, -1));

        panelSideBar.add(panelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 320, 50));

        panelCourseList.setBackground(new java.awt.Color(255, 102, 102));
        panelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/list.png"))); // NOI18N
        btnCourseList.setText("        Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 260, -1));

        panelSideBar.add(panelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 320, 50));

        panelViewAllRecords.setBackground(new java.awt.Color(255, 102, 102));
        panelViewAllRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelViewAllRecords.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecords.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnViewAllRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/view all record.png"))); // NOI18N
        btnViewAllRecords.setText("        View All Records");
        btnViewAllRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseExited(evt);
            }
        });
        panelViewAllRecords.add(btnViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        panelSideBar.add(panelViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 320, 50));

        panelBack.setBackground(new java.awt.Color(255, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managment_syatem/icon/left-arrow.png"))); // NOI18N
        btnBack.setText("        Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 260, -1));

        panelSideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 320, 50));

        getContentPane().add(panelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 1040));

        panelParent.setBackground(new java.awt.Color(255, 204, 204));
        panelParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChequeNo.setBackground(new java.awt.Color(51, 51, 51));
        lblChequeNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChequeNo.setText("Cheque No :");
        panelParent.add(lblChequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblReceiptNo.setBackground(new java.awt.Color(51, 51, 51));
        lblReceiptNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReceiptNo.setText("Receipt no :  MLV-");
        panelParent.add(lblReceiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblDdNo.setBackground(new java.awt.Color(51, 51, 51));
        lblDdNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDdNo.setText("DD no :");
        panelParent.add(lblDdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblModeOfPayment.setBackground(new java.awt.Color(51, 51, 51));
        lblModeOfPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModeOfPayment.setText(" Mode of payment : ");
        panelParent.add(lblModeOfPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtGSTNo.setBackground(new java.awt.Color(51, 51, 51));
        txtGSTNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGSTNo.setText(" sffsfe22");
        panelParent.add(txtGSTNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 70, -1));

        lblDate.setBackground(new java.awt.Color(51, 51, 51));
        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setText("  Date : ");
        panelParent.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));
        panelParent.add(txtReceiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, -1));
        panelParent.add(txtChequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, -1));
        panelParent.add(DateChosser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 140, -1));

        panelChild.setBackground(new java.awt.Color(255, 204, 204));
        panelChild.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPaymentCollage.setBackground(new java.awt.Color(51, 51, 51));
        lblPaymentCollage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPaymentCollage.setText("the following paymemnts the collage office for the year ");
        panelChild.add(lblPaymentCollage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblTo.setBackground(new java.awt.Color(51, 51, 51));
        lblTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTo.setText("to");
        panelChild.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 20, -1));
        panelChild.add(txtLastDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 80, -1));

        lblAmount.setBackground(new java.awt.Color(51, 51, 51));
        lblAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmount.setText("Amount");
        panelChild.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));
        panelChild.add(txtFirstDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, -1));

        lblReceiverSignature.setBackground(new java.awt.Color(51, 51, 51));
        lblReceiverSignature.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReceiverSignature.setText("Receiver signature");
        panelChild.add(lblReceiverSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, -1));

        lblRecievedFrom.setBackground(new java.awt.Color(51, 51, 51));
        lblRecievedFrom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRecievedFrom.setText("Recieved From :");
        panelChild.add(lblRecievedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        panelChild.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 820, 10));
        panelChild.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 820, 10));

        lblCourse.setBackground(new java.awt.Color(51, 51, 51));
        lblCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCourse.setText("Course :");
        panelChild.add(lblCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblRemark.setBackground(new java.awt.Color(51, 51, 51));
        lblRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemark.setText("Remark :");
        panelChild.add(lblRemark, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lblSgst.setBackground(new java.awt.Color(51, 51, 51));
        lblSgst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSgst.setText("SGST 9% ");
        panelChild.add(lblSgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));
        panelChild.add(txtSumTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 150, -1));
        panelChild.add(txtTotalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 410, -1));
        panelChild.add(txtCgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 150, -1));

        txtAmountFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountFirstActionPerformed(evt);
            }
        });
        panelChild.add(txtAmountFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 150, -1));
        panelChild.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 180, 10));
        panelChild.add(txtSgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 150, -1));

        lblSrNo.setBackground(new java.awt.Color(51, 51, 51));
        lblSrNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSrNo.setText("Sr No ");
        panelChild.add(lblSrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        panelChild.add(txtHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 400, -1));

        jScrollPane1.setViewportView(textPaneRemark);

        panelChild.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 410, 90));

        lblTotalInWords.setBackground(new java.awt.Color(51, 51, 51));
        lblTotalInWords.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalInWords.setText("Total in words : ");
        panelChild.add(lblTotalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        panelChild.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 190, 20));

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Roll No :");
        panelChild.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        panelChild.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        lblHead.setBackground(new java.awt.Color(51, 51, 51));
        lblHead.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHead.setText("Head ");
        panelChild.add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        lblCgst.setBackground(new java.awt.Color(51, 51, 51));
        lblCgst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCgst.setText("CGST 9%");
        panelChild.add(lblCgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        comboBoxCourse1.setMaximumRowCount(5);
        comboBoxCourse1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAVA", "WEB DEVELOPMENT", "SPRINGBOOT", "C", "C++", "PYTHON" }));
        comboBoxCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCourse1ActionPerformed(evt);
            }
        });
        panelChild.add(comboBoxCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 350, -1));

        txtHead1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHead1ActionPerformed(evt);
            }
        });
        panelChild.add(txtHead1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 400, -1));
        panelChild.add(txtRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 90, -1));

        panelParent.add(panelChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 870, 900));
        panelParent.add(txtDDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, -1));

        comboBoxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "Cheque", "Cash", "Card" }));
        comboBoxPayment.setSelectedIndex(2);
        comboBoxPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPaymentActionPerformed(evt);
            }
        });
        panelParent.add(comboBoxPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));
        panelParent.add(txtBankName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        lblBankName1.setBackground(new java.awt.Color(51, 51, 51));
        lblBankName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBankName1.setText("Bank Name : ");
        panelParent.add(lblBankName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblGSTNo1.setBackground(new java.awt.Color(51, 51, 51));
        lblGSTNo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGSTNo1.setText("  GSTIN:    ");
        panelParent.add(lblGSTNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 60, -1));

        getContentPane().add(panelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 1420, 1040));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        // TODO add your handling code here:
            Color clr=new Color(255,204,204);
            panelLogOut.setBackground(clr);
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(255,102,102);
        panelLogOut.setBackground(clr);
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
       Color clr=new Color(255,204,204);
            panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
         Color clr=new Color(255,102,102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordsMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(255,204,204);
            panelSearchRecords.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordsMouseEntered

    private void btnSearchRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordsMouseExited
        // TODO add your handling code here:
        Color clr=new Color(255,102,102);
        panelSearchRecords.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordsMouseExited

    private void btnEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(255,204,204);
            panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseEntered

    private void btnEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseExited
        // TODO add your handling code here:
         Color clr=new Color(255,102,102);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseExited

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(255,204,204);
            panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        // TODO add your handling code here:
         Color clr=new Color(255,102,102);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(255,204,204);
            panelViewAllRecords.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordsMouseEntered

    private void btnViewAllRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseExited
        // TODO add your handling code here:
          Color clr=new Color(255,102,102);
        panelViewAllRecords.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordsMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(255,204,204);
            panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr=new Color(255,102,102);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void comboBoxPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPaymentActionPerformed
        // TODO add your handling code here:
        if(comboBoxPayment.getSelectedIndex() == 0){
            lblDdNo.setVisible(true);
            txtDDNo.setVisible(true);
            lblChequeNo.setVisible(false);
            txtChequeNo.setVisible(false); 
             lblBankName1.setVisible(true);
            txtBankName1.setVisible(true);
        }
         if(comboBoxPayment.getSelectedIndex() == 1){
            lblDdNo.setVisible(false);
            txtDDNo.setVisible(false);
            lblChequeNo.setVisible(true);
            txtChequeNo.setVisible(true); 
            lblBankName1.setVisible(true);
            txtBankName1.setVisible(true);
        }
          if(comboBoxPayment.getSelectedIndex() == 2){
            lblDdNo.setVisible(false);
            txtDDNo.setVisible(false);
            lblChequeNo.setVisible(false);
            txtChequeNo.setVisible(false);  
             lblBankName1.setVisible(false);
            txtBankName1.setVisible(false);
        }
          if(comboBoxPayment.getSelectedItem().equals("Card")){
            lblDdNo.setVisible(false);
            txtDDNo.setVisible(false);
            txtGSTNo.setVisible(true);
            txtGSTNo.setVisible(true);
            lblChequeNo.setVisible(false);
            txtChequeNo.setVisible(false);  
            lblBankName1.setVisible(true);
            txtBankName1.setVisible(true);
        }
    }//GEN-LAST:event_comboBoxPaymentActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if(validation() == true){
           String result= insertData();
           if(result.equals("Success")){
            JOptionPane.showMessageDialog(this, "Records Insert SuccessFully");
            printReceipt p =new printReceipt();
            p.setVisible(true);
            this.dispose();
           }
           else{
              JOptionPane.showMessageDialog(this, "Records Insert Failed"); 
           }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtAmountFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountFirstActionPerformed
             Float amnt=Float.parseFloat(txtAmountFirst.getText());
             Float cgst=(float)(amnt * 0.09);
             Float sgst=(float)(amnt * 0.09);
             txtCgst.setText(cgst.toString());
             txtSgst.setText(sgst.toString());
             float total=amnt+cgst+sgst;
             txtSumTotal.setText(Float.toString(total));
             txtTotalInWords.setText(NumberToWordsConverter.convert((int)total)+" only /-");
    }//GEN-LAST:event_txtAmountFirstActionPerformed

    private void txtHead1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHead1ActionPerformed

    }//GEN-LAST:event_txtHead1ActionPerformed

    private void comboBoxCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCourse1ActionPerformed
        // TODO add your handling code here:
        txtHead1.setText(comboBoxCourse1.getSelectedItem().toString());
    }//GEN-LAST:event_comboBoxCourse1ActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
       HomePage home=new HomePage();
       home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnSearchRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordsMouseClicked
        SearchRecords searchrecords=new SearchRecords();
        searchrecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchRecordsMouseClicked

    private void btnEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseClicked
       EditCourse edit=new EditCourse();
       edit.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnEditCourseMouseClicked

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseClicked

    private void btnViewAllRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseClicked
       ViewAllRecords viewrecords=new ViewAllRecords();
       viewrecords.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnViewAllRecordsMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
       HomePage home=new HomePage();
       home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnLogOutMouseClicked
    public int getReceiptNo(){
        int receipt_no=0;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_managment?zeroDateTimeBehavior=CONVERT_TO_NULL","root",""); 
            PreparedStatement pst=con.prepareStatement("select max(recieptNo) from fees_details");
            ResultSet rs=pst.executeQuery();
            if(rs.next() == true){
                receipt_no=rs.getInt(1);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return receipt_no+1;
    }
    public String insertData(){
        String status="";
        int recieptNo=Integer.parseInt(txtReceiptNo.getText());
        String studentName=txtHead.getText();
        String rollNo=txtRollNo.getText();
        String paymentMode=comboBoxPayment.getSelectedItem().toString();
        String chequeNo=txtChequeNo.getText();
        String bankName=txtBankName1.getText();
        String ddNo=txtDDNo.getText();
        String courseName=txtHead1.getText();
        String gstin=txtGSTNo.getText();
        float totalAmount=Float.parseFloat(txtSumTotal.getText());
        SimpleDateFormat dateFormat =new SimpleDateFormat("yyyy-MM-dd");
        String date=dateFormat.format(DateChosser.getDate());
        float initialAmount=Float.parseFloat(txtAmountFirst.getText());
        float cgst=Float.parseFloat(txtCgst.getText());
        float sgst=Float.parseFloat(txtSgst.getText());
        String totalInWords=txtTotalInWords.getText();
        String remark=textPaneRemark.getText();
        int year1=Integer.parseInt(txtFirstDate.getText());
        int year2=Integer.parseInt(txtLastDate.getText());
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_managment?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");  
        PreparedStatement pst=con.prepareStatement("insert into fees_details values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        pst.setInt(1,recieptNo);
        pst.setString(2, studentName);
        pst.setString(3,rollNo);
        pst.setString(4,paymentMode);
        pst.setString(5,chequeNo);
        pst.setString(6, bankName);
        pst.setString(7,ddNo);
        pst.setString(8,courseName);
        pst.setString(9,gstin);
        pst.setFloat(10,totalAmount);
        pst.setString(11,date);
        pst.setFloat(12, initialAmount);
        pst.setFloat(13,cgst);
        pst.setFloat(14,sgst);
        pst.setString(15,totalInWords);
        pst.setString(16,remark);
        pst.setInt(17,year1);
        pst.setInt(18,year2);
        int rowCount=pst.executeUpdate();
        if(rowCount==1){
            status="Success";   
        }
        else{
            status="Failed";
        }
    }catch(Exception e){
        e.printStackTrace();
    }
    return status;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChosser;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEditCourse;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel btnSearchRecords;
    private javax.swing.JLabel btnViewAllRecords;
    private javax.swing.JComboBox<String> comboBoxCourse1;
    private javax.swing.JComboBox<String> comboBoxPayment;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblCgst;
    private javax.swing.JLabel lblChequeNo;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDdNo;
    private javax.swing.JLabel lblGSTNo1;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblModeOfPayment;
    private javax.swing.JLabel lblPaymentCollage;
    private javax.swing.JLabel lblReceiptNo;
    private javax.swing.JLabel lblReceiverSignature;
    private javax.swing.JLabel lblRecievedFrom;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JLabel lblSgst;
    private javax.swing.JLabel lblSrNo;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblTotalInWords;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelChild;
    private javax.swing.JPanel panelCourseList;
    private javax.swing.JPanel panelEditCourse;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogOut;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelSearchRecords;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JPanel panelViewAllRecords;
    private javax.swing.JTextPane textPaneRemark;
    private javax.swing.JTextField txtAmountFirst;
    private javax.swing.JTextField txtBankName1;
    private javax.swing.JTextField txtCgst;
    private javax.swing.JTextField txtChequeNo;
    private javax.swing.JTextField txtDDNo;
    private javax.swing.JTextField txtFirstDate;
    private javax.swing.JLabel txtGSTNo;
    private javax.swing.JTextField txtHead;
    private javax.swing.JTextField txtHead1;
    private javax.swing.JTextField txtLastDate;
    private javax.swing.JTextField txtReceiptNo;
    private javax.swing.JTextField txtRollNo;
    private javax.swing.JTextField txtSgst;
    private javax.swing.JTextField txtSumTotal;
    private javax.swing.JTextField txtTotalInWords;
    // End of variables declaration//GEN-END:variables
}
